# .github/workflows/ci.yml
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  earthly:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions/setup-earthly@v1
        with:
          version: v0.6.14
      - uses: actions/checkout@v2
      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true
      - name: Run build
        run: earthly --ci +all
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Ceedling
        run: sudo gem install ceedling --no-user-install
      - name: Install automake
        run: HOMEBREW_NO_AUTO_UPDATE=1 brew install autoconf automake libtool
      - name: Build dependencies
        run: ceedling project:macos clobber dependencies:make
      - name: Run build and test
        run: ceedling project:macos
